домашня робота до 4 заняття
LilianaLukash/PythonStudy pull request #2
Opened 2022-12-07 20:39 UTC by LilianaLukash

домашня робота до 4 заняття

2022-12-07 21:05 UTC, klymenok requested changes

2022-12-07 21:05 UTC, klymenok commented on home-work-04.py
> +try:
You can complete this task without using try...except for now. Try to solve it using if...elif...else conditions and functions for strings (like .isdigit())

2022-12-07 22:13 UTC, LilianaLukash commented on home-work-04.py
> +try:
Please look again without try...except and with if...

2022-12-08 18:23 UTC, klymenok approved these changes
Well done

2022-12-12 19:37 UTC, merged