Homework12
LilianaLukash/PythonStudy pull request #8
Opened 2023-01-15 23:26 UTC by LilianaLukash

2023-01-16 14:13 UTC, acman requested changes
LGTM! there are only small fixes that should be provided

2023-01-16 14:13 UTC, acman commented on 12/function_calls.txt
> +my_function called at 1673820764.4037929
better not add the environmental and test files to commit like .idea, .txt, only code

2023-01-16 14:13 UTC, acman commented on 12/hw.py
> +def mydecorator(func):
better name decorator about how it works like `log_decorator`, `log_execution_time_decorator`.

2023-01-16 14:13 UTC, acman commented on 12/hw.py
> +    print("Ola amigos!")
Hola! :)

2023-01-16 14:13 UTC, acman commented on 12/hw13a.py
> +    with open("phonebook.txt", "r") as book:
`phonebook.json`

2023-01-16 14:13 UTC, acman commented on 12/hw13c.py
> +raise MyCustomException()
better to add empty line at the end of all python files

2023-01-16 16:24 UTC, LilianaLukash reviewed
corrected

2023-01-16 16:24 UTC, LilianaLukash commented on 12/hw.py
> +def mydecorator(func):
Thanks, Corrected

2023-01-16 16:24 UTC, LilianaLukash commented on 12/hw.py
> +    print("Ola amigos!")
I am in Portugal and have to learn Portuguise) So here its Ola))

2023-01-16 16:24 UTC, LilianaLukash commented on 12/hw13a.py
> +    with open("phonebook.txt", "r") as book:
corrected in new commit

2023-01-16 16:24 UTC, LilianaLukash commented on 12/hw13c.py
> +raise MyCustomException()
corrected

2023-01-18 11:41 UTC, acman approved these changes
nice job! but next time dont add `.idea/` directory to commit or create .gitignore for it

2023-01-21 23:29 UTC, merged